### ISSUE TITLE
kilocalories per mol/mole

### ISSUE THREAD

**Issue by richardjgowers** [openforcefield/openff-units#22]
openff units has "kilocalories_per_mol" and openmm units "kilocalories_per_mole".

Is this package meant to align with naming in openmm?  &if so would it be helpful to at least create aliases for each unit?

**Comment by mattwthompson** [comment]
I haven't gone out of my way to avoid it but I also have missed some cases like this. I ran into something like this in the past (https://github.com/openforcefield/openff-units/issues/7) but can't recall why I haven't run into this particular headache - I suppose I'm not parsing directly from a string as often as you are?

Anyway, I'm happy to add aliases wherever they make things convenient.

**Comment by mattwthompson** [comment]
This specific one I can't reproduce in the same way:

```python3
In [1]: from openmm import unit as openmm_unit

In [2]: from openff.units import unit
/Users/mwt/miniconda3/envs/openff-dev/lib/python3.8/site-packages/setuptools/version.py:1: UserWarning: Module openff was already imported from None, but /Users/mwt/software/openff-units is being added to sys.path
  import pkg_resources

In [3]: unit.kilocalories_per_mole
Out[3]: <Unit('kilocalories_per_mole')>

In [4]: openmm_unit.kilocalories_per_mole
Out[4]: Unit({BaseUnit(base_dim=BaseDimension("amount"), name="mole", symbol="mol"): -1.0, ScaledUnit(factor=4.184, master=kilojoule, name='kilocalorie', symbol='kcal'): 1.0})

In [5]: unit.kilocalories_per_mol
---------------------------------------------------------------------------
UndefinedUnitError                        Traceback (most recent call last)
Input In [5], in <cell line: 1>()
<snipping the traceback>

UndefinedUnitError: 'kilocalories_per_mol' is not defined in the unit registry

In [6]: openmm_unit.kilocalories_per_mol
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 openmm_unit.kilocalories_per_mol

AttributeError: module 'openmm.unit' has no attribute 'kilocalories_per_mol'
```

but this is assuming you'd be grabbing the module-level objects. Again I'm happy to create aliases wherever useful and commonly-treaded, I'm just not sure how to find them without either waiting for user reports or doing something [rigorously silly](https://gist.github.com/mattwthompson/de5f75b6fc2efa9b4b125b0421d2a091) like I just found myself trying.

**Comment by mattwthompson** [comment]
I think this is supported https://github.com/openforcefield/openff-units/blob/0.2.2/openff/units/data/defaults.txt#L137-L142
