### ISSUE TITLE
`to_openmm` fails in cases when OpenMM's unit registry differs from Pint's

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openforcefield/openff-units#29]
The easiest way to get Boltzmann's constant is

```python
from openff.units import unit

k_B = 1 * unit.k_B
```

This produces a quantity with units `boltzmann_constant`. OpenMM has no such unit, so calling `to_openmm` raises an exception:

```python
>>> from openff.units import unit
>>> from openff.units.openmm import to_openmm
>>>
>>> to_openmm(1 * unit.k_B)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joshmitchell/conda/envs/units-docs/lib/python3.10/site-packages/openff/utilities/utilities.py", line 75, in wrapper
    return function(*args, **kwargs)
  File "/home/joshmitchell/Documents/openff/openff-units/openff/units/openmm.py", line 159, in to_openmm
    openmm_unit_ = string_to_openmm_unit(unit_string)
  File "/home/joshmitchell/Documents/openff/openff-units/openff/units/openmm.py", line 125, in string_to_openmm_unit
    output_unit = _ast_eval(ast.parse(unit_string, mode="eval").body)  # type: ignore
  File "/home/joshmitchell/Documents/openff/openff-units/openff/units/openmm.py", line 97, in _ast_eval
    b = getattr(openmm_unit, node.id)
AttributeError: module 'openmm.unit' has no attribute 'boltzmann_constant'
```

A workaround is to convert to base units first:

```python
>>> from openff.units import unit
>>> from openff.units.openmm import to_openmm
>>>
>>> to_openmm((1 * unit.k_B).to_base_units())
Quantity(value=1.380649e-23, unit=kilogram*meter**2/(second**2*kelvin))
```

So a fix might be to blindly do this inside `to_openmm`, though this means the precise units will change on conversion which may have floating point precision implications. Better might be to try converting exactly, and if this fails to call to_base_units.

`to_base_units` is also a bit of a pain coz its in kg/m/s/C units. An alternative method in Da/nm/ps/e might be worthwhile too (GROMACS [uses these](https://manual.gromacs.org/documentation/2021/reference-manual/definitions.html#md-units), they're nice because the derived unit of energy works out to be kJ/mol).

**Comment by mattwthompson** [comment]
I'm trying to untangle the specific issue and a more general issue. I see here the code choking when

```
In [1]: from openmm import unit

In [2]: getattr(unit, "boltzmann_constant")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 getattr(unit, "boltzmann_constant")

AttributeError: module 'openmm.unit' has no attribute 'boltzmann_constant'
```

I was a bit confused by the initial title since I `k_B` in your example was still a `unit.Quantity`, but now I see that OpenMM simply doesn't have a concept of Boltzmann's constant being treated as a unit.

> A workaround is to convert to base units first:

It's hard to think of a better solution, i.e. the output of `to_openmm(1.0 * unit.k_B)` will probably be messy.

I'll continue in the linked PR!
