### ISSUE TITLE
Handling `None` in unit conversions

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-units#37]
I had not considered how to deal with cases such as `from_openmm(None)` and it can lead to some opaque issues for users and downstream programs: https://github.com/openforcefield/openff-evaluator/issues/450

I can think of two ways of handling this:

1. Error out if `None` is passed
2. Return `None` if `None` is passed

My preference is to be explicit with 1.

**Comment by j-wags** [comment]
If we do 1, then the error message should suggest a workaround. Cribbing from the body post of https://github.com/openforcefield/openff-evaluator/issues/450, it could recommend something like `openmm_val = None if self.ensemble is None else to_openmm(openff_val)`

**Comment by j-wags** [comment]
But yeah, I generally agree that 1 is a simpler, more maintainable feature and is probably the right way for us to go!

**Comment by mattwthompson** [comment]
Thanks for the feedback - I'll push ahead with this choice

> If we do 1, then the error message should suggest a workaround.

I disagree somewhat; in the Evaluator case that triggered this, the variable could be `None` or a quantity, but there's also the simpler case of a user errantly passing something that can only be `None`. I think it's a slight over-reach for this package to make such assumptions about what's passed in. Here's what it looks like in #32:

```python3
>>> from openff.units.openmm import from_openmm
>>> from_openmm(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/miniconda3/envs/openff-units-test/lib/python3.9/site-packages/openff/utilities/utilities.py", line 75, in wrapper
    return function(*args, **kwargs)
  File "/Users/mattthompson/software/openff-units/openff/units/openmm.py", line 154, in from_openmm
    raise NoneQuantityError(
openff.units.exceptions.NoneQuantityError: Input is None, expected an (OpenMM) Quantity object.
```

I think this exception bubbling out would have made the issue easier to debug, hopefully with something about `pressure` in the traceback
