### ISSUE TITLE
pint 0.20 breaks everything

### ISSUE THREAD

**Issue by richardjgowers** [openforcefield/openff-units#50]
pint v0.20 did some refactoring, so you now get `ModuleNotFoundError: No module named 'pint.measurement'`

Tried a simple rename in #49 and got more errors, what fun.

**Comment by mattwthompson** [comment]
Thanks, we re-built the last version with a pin (`openff-units-0.1.8-somethingorother_1`) but I'll soon look into a proper fix that doesn't involve upper constraints

**Comment by mattwthompson** [comment]
Resolved with https://github.com/openforcefield/openff-units/releases/tag/0.2.0
